### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gizmokrang** [habanoz/dune-reward-distributor#2]
:~/dune-reward-distributor$ python3 src/main.py --help
Traceback (most recent call last):
  File "src/main.py", line 11, in <module>
    from api.provider_factory import ProviderFactory
  File "/home/dunebaker/dune-reward-distributor/src/api/provider_factory.py", line 1, in <module>
    from rpc.lrpc_reward_api import LRpcRewardApiImpl
  File "/home/dunebaker/dune-reward-distributor/src/rpc/lrpc_reward_api.py", line 10, in <module>
    from dunscan.dunscan_reward_api import DunScanRewardApiImpl
  File "/home/dunebaker/dune-reward-distributor/src/dunscan/dunscan_reward_api.py", line 5, in <module>
    from dunscan.dunscan import DunScanRewardProviderHelper
ModuleNotFoundError: No module named 'dunscan.dunscan'

**Comment by habanoz** [comment]
It should be fixed now.

**Comment by habanoz** [comment]
Closing
