### ISSUE TITLE
stopping DRD from systemctl cannot remove lock file

### ISSUE THREAD

**Issue by utdrmac** [habanoz/dune-reward-distributor#5]
```
things1.ewr1 python3[16127]: Traceback (most recent call last):
things1.ewr1 python3[16127]: File "/home/bakingdunes/dune-reward-distributor/src/main.py", line 259, in <module>
things1.ewr1 python3[16127]: main(args)
things1.ewr1 python3[16127]: File "/home/bakingdunes/dune-reward-distributor/src/main.py", line 170, in main
things1.ewr1 python3[16127]: while life_cycle.is_running(): time.sleep(10)
things1.ewr1 python3[16127]: File "/home/bakingdunes/dune-reward-distributor/src/util/process_life_cycle.py", line 39, in stop_handler
things1.ewr1 python3[16127]: self.stop()
things1.ewr1 python3[16127]: File "/home/bakingdunes/dune-reward-distributor/src/util/process_life_cycle.py", line 30, in stop
things1.ewr1 python3[16127]: self.lock_file.release()
things1.ewr1 python3[16127]: File "/home/bakingdunes/dune-reward-distributor/src/util/lock_file.py", line 22, in release
things1.ewr1 python3[16127]: os.remove(self.lock_file_path)
things1.ewr1 python3[16127]: FileNotFoundError: [Errno 2] No such file or directory: './lock'
things1.ewr1 python3[16127]: 2019-10-14 16:35:31,367 - MainThread - Application stop handler called: 15
things1.ewr1 python3[16127]: 2019-10-14 16:35:31,368 - MainThread - --------------------------------------------------------
things1.ewr1 python3[16127]: 2019-10-14 16:35:31,369 - MainThread - Sensitive operations are in progress!
things1.ewr1 python3[16127]: 2019-10-14 16:35:31,369 - MainThread - Please wait while the application is being shut down!
things1.ewr1 python3[16127]: 2019-10-14 16:35:31,369 - MainThread - --------------------------------------------------------
things1.ewr1 python3[16127]: Exception ignored in: <module 'threading' from '/usr/lib64/python3.6/threading.py'>
things1.ewr1 python3[16127]: Traceback (most recent call last):
things1.ewr1 python3[16127]: File "/usr/lib64/python3.6/threading.py", line 1294, in _shutdown
things1.ewr1 python3[16127]: t.join()
things1.ewr1 python3[16127]: File "/usr/lib64/python3.6/threading.py", line 1056, in join
things1.ewr1 python3[16127]: self._wait_for_tstate_lock()
things1.ewr1 python3[16127]: File "/usr/lib64/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
things1.ewr1 python3[16127]: elif lock.acquire(block, timeout):
things1.ewr1 python3[16127]: File "/home/bakingdunes/dune-reward-distributor/src/util/process_life_cycle.py", line 39, in stop_handler
things1.ewr1 python3[16127]: self.stop()
things1.ewr1 python3[16127]: File "/home/bakingdunes/dune-reward-distributor/src/util/process_life_cycle.py", line 30, in stop
things1.ewr1 python3[16127]: self.lock_file.release()
things1.ewr1 python3[16127]: File "/home/bakingdunes/dune-reward-distributor/src/util/lock_file.py", line 22, in release
things1.ewr1 python3[16127]: os.remove(self.lock_file_path)
things1.ewr1 python3[16127]: FileNotFoundError: [Errno 2] No such file or directory: './lock'
things1.ewr1 systemd[1]: dune-reward.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by Twente-Mining** [comment]
You can manually remove the lock file if this is a one time event

**Comment by utdrmac** [comment]
@Twente-Mining it's not a one-time event. Not sure if this affects TRD as well. Either the script needs to better understand it's own paths to files, or the systemd template should be updated in some way.
